# RedVision / TVMS CAN bridge — device config to flash.

substitutions:
  device_name: redvision_can_bridge
  friendly_name: Redvision CAN Bridge

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  comment: "RedVision/TVMS CAN bridge v2; single redarc component"

esp32:
  board: m5stack-atom
  framework:
    type: esp-idf

logger:
  level: INFO
  baud_rate: 0

api:
  encryption:
    key: !secret api_pass

ota:
  - platform: esphome
    password: !secret ota_pass

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

captive_portal:

external_components:
  - source:
      type: git
      url: https://github.com/dev8edss/Redarc-reverse-engineering
      ref: dev
    refresh: 0s
    components:
      - redarc

redarc:
  canbus:

  # host_address: "0xFF"
  # filter_interval: 5s
  # history_poll_interval: 60s

  battery_sensor:
    - id: Battery
      source_address: 0x08

  manager:
    - id: Manager30
      source_address: 0x01
      battery_sensor_id: Battery

  redvision_display:
    - id: Redvision1
      source_address: 0x20
    - id: Redvision2
      source_address: 0x21

  tvms_rogue:
    - id: TVMS_Rogue
      source_address: 0x30
      transition_length: 0s  # fade time for outputs discovered as dimmable

  tvms_1280:
    - id: TVMS1280
      source_address: 0x24
